# Site settings
name: BromitLon
title: BromitLon | Personal Page For Public
description: I'm BromitLon, a design-minded one who is Still learning New Stuff, FOSS Supporter & Cyber Nerd
url: https://bromit.github.io/
baseurl: ''
email: hi@bromit.slmail.me
cover: https://bromitlon.github.io/img/og.png
logo: https://bromitlon.github.io/img/emojis/technologist.png
resume: https://bromitlon.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@bromit.slmail.me
  - title: twitter
    url: https://twitter.com/bromitlon
  - title: instagram
    url: https://instagram.com/bromitlon
  - title: github
    url: https://github.com/bromitlon

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
